In [ ]:
# Mount Google Drive folder 
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#importing libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [ ]:
#importing the data set

DIR = '/content/drive/MyDrive/Colab Notebooks/AML_LAB/DataPreprocessing/'
FILENAME = 'bestsellers.csv'
os.chdir(DIR)
dataset = pd.read_csv(DIR + FILENAME)
dataset.head(20)

Name  ...        Genre
0                       10-Day Green Smoothie Cleanse  ...  Non Fiction
1                                   11/22/63: A Novel  ...      Fiction
2             12 Rules for Life: An Antidote to Chaos  ...  Non Fiction
3                              1984 (Signet Classics)  ...      Fiction
4   5,000 Awesome Facts (About Everything!) (Natio...  ...  Non Fiction
5       A Dance with Dragons (A Song of Ice and Fire)  ...      Fiction
6   A Game of Thrones / A Clash of Kings / A Storm...  ...      Fiction
7                      A Gentleman in Moscow: A Novel  ...      Fiction
8       A Higher Loyalty: Truth, Lies, and Leadership  ...  Non Fiction
9                           A Man Called Ove: A Novel  ...      Fiction
10                          A Man Called Ove: A Novel  ...      Fiction
11  A Patriot's History of the United States: From...  ...  Non Fiction
12                            A Stolen Life: A Memoir  ...  Non Fiction
13                   A Wrinkle in Time (Time Quintet)  ...      Fiction
14  Act Like a Lady, Think Like a Man: What Men Re...  ...  Non Fiction
15  Adult Coloring Book Designs: Stress Relief Col...  ...  Non Fiction
16  Adult Coloring Book: Stress Relieving Animal D...  ...  Non Fiction
17     Adult Coloring Book: Stress Relieving Patterns  ...  Non Fiction
18  Adult Coloring Books: A Coloring Book for Adul...  ...  Non Fiction
19                                 Alexander Hamilton  ...  Non Fiction

[20 rows x 7 columns]

In [ ]:
#create matrix of all independent variable

x = dataset.iloc[:,:-1].values
x

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, 17350.0, 8.0,
        2016],
       ['11/22/63: A Novel', 'Stephen King', 4.6, 2052.0, 22.0, 2011],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, 18979.0, 15.0, 2018],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2017],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2018],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2019]], dtype=object)

In [ ]:
#create a matrix  of dependent variable

y = dataset.iloc[:,6].values
y

array(['Non Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non F

In [ ]:
#Handling missing data

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = 'NaN', strategy = 'mean')
imputer = SimpleImputer().fit(x[:, 2:6]) 
x[:, 2:6] = imputer.transform(x[:, 2:6])
print(x[0:10,:])

[['10-Day Green Smoothie Cleanse' 'JJ Smith' 4.7 17350.0 8.0 2016.0]
 ['11/22/63: A Novel' 'Stephen King' 4.6 2052.0 22.0 2011.0]
 ['12 Rules for Life: An Antidote to Chaos' 'Jordan B. Peterson' 4.7
  18979.0 15.0 2018.0]
 ['1984 (Signet Classics)' 'George Orwell' 4.7 21424.0 6.0 2017.0]
 ['5,000 Awesome Facts (About Everything!) (National Geographic Kids)'
  'National Geographic Kids' 4.8 7665.0 12.0 2019.0]
 ['A Dance with Dragons (A Song of Ice and Fire)' 'George R. R. Martin'
  4.4 12643.0 11.0 2011.0]
 ['A Game of Thrones / A Clash of Kings / A Storm of Swords / A Feast of Crows / A Dance with Dragons'
  'George R. R. Martin' 4.7 19735.0 30.0 2014.0]
 ['A Gentleman in Moscow: A Novel' 'Amor Towles' 4.7 19699.0 15.0 2017.0]
 ['A Higher Loyalty: Truth, Lies, and Leadership' 'James Comey'
  4.6180656934306565 5983.0 3.0 2018.0]
 ['A Man Called Ove: A Novel' 'Fredrik Backman' 4.6 23848.0 8.0 2016.0]]


In [ ]:
#Encoding the categorical data
#Encoding independent variable

from sklearn.preprocessing import LabelEncoder,OneHotEncoder

labelencoder_x = LabelEncoder()
x[:,0] = labelencoder_x.fit_transform(x[:,0])
x

array([[0, 'JJ Smith', 4.7, 17350.0, 8.0, 2016.0],
       [1, 'Stephen King', 4.6, 2052.0, 22.0, 2011.0],
       [2, 'Jordan B. Peterson', 4.7, 18979.0, 15.0, 2018.0],
       ...,
       [350, 'Jen Sincero', 4.7, 14331.0, 8.0, 2017.0],
       [350, 'Jen Sincero', 4.7, 14331.0, 8.0, 2018.0],
       [350, 'Jen Sincero', 4.7, 14331.0, 8.0, 2019.0]], dtype=object)

In [ ]:
#dummy Encoding
onehotencoder = OneHotEncoder()
x = onehotencoder.fit_transform(x).toarray()
x

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
#Encoding the dependent varaialbe
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,

In [ ]:
#splitting the dataste into train set and test test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=0)
x_train.astype(int)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#Feature scaling

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)
x_test

array([[ 0.        , -0.09578263,  0.        , ..., -0.21821789,
        -0.24019223,  3.16227766],
       [ 0.        , -0.09578263,  0.        , ..., -0.21821789,
        -0.24019223, -0.31622777],
       [ 0.        , -0.09578263,  0.        , ..., -0.21821789,
        -0.24019223, -0.31622777],
       ...,
       [ 0.        , -0.09578263,  0.        , ..., -0.21821789,
        -0.24019223, -0.31622777],
       [ 0.        , -0.09578263,  0.        , ..., -0.21821789,
        -0.24019223, -0.31622777],
       [ 0.        , -0.09578263,  0.        , ..., -0.21821789,
        -0.24019223, -0.31622777]])